message:
  join: "{PLAYER} a rejoint la partie"
  quit: "{PLAYER} a quitter la partie"
  game-join: "{PLAYER} ragarde désormais la partie"
  game-quit: "{PLAYER} ne regarde plus la partie"
  kit-selected: "le kit a été changer avec succès"
  starting: "la partie commence dans {TIME} secondes"
  stop-starting: "§4la partie a à été arrèter, raison : manque de joueur"
  start: "la partie commence maintenant"
  win: "§6l'équipe {TEAM} a gagné !!!"
  no-match: "§6les deux équipes sont ex-éco"
  relaunch: "une nouvelle partie recommence dans {TIME} secondes"

manager:
  min-size: 2
  max-size: 8
  timer:
    starting-time: 5
    playing-time: 45
    finish-time: 5